### ISSUE TITLE
Support Gradle / Maven Repository

### ISSUE THREAD

**Issue by Thorsten1976** [Tealium/tealium-android#1]
Updating local dependencies (libs) requires additional build steps, especially for AAR artefacts.
Please support a public repository to use Gradle's target: i. e. compile '...' 

This also supports versioning.

**Comment by jalakoo** [comment]
Thorsten,
Gradle support is on our roadmap, unfortunately an availability date has not yet been set.

**Comment by craigrouse** [comment]
@Thorsten1976 FYI, we now have a maven repo available 

https://community.tealiumiq.com/t5/Mobile-Libraries/Mobile-110-Getting-started-with-Android-amp-Android-TV-5-x/ta-p/15578#library_setup
