### ISSUE TITLE
Overriding the location of the mobile.html file doesn't actually do anything 

### ISSUE THREAD

**Issue by langerhans** [Tealium/tealium-android#10]
Steps to reproduce:
1. `tealiumConfig.setOverrideTagManagementUrl("https://mydomain.com/path/to/mobile.html");`
2. Observe network requests in e.g. Fiddler

It appears that even though a different URL is set in the `Tealium.Config` object that is used when creating the instance (verified by logging its `toString()` representation), the SDK actually still uses the tiqcdn domain. Is this a bug or am I misunderstanding the use of `setOverrideTagManagementUrl()`. Reason I ask is that we plan to host the file on our own CDN.

**Comment by tamayok** [comment]
@langerhans I'll double check if this a bug, but this is the first time this issue comes up. In the meantime, can you check your mobile publish settings in Tealium TiQ, and make sure that Tag Management is enabled and Tealium Collect is disabled??

**Comment by langerhans** [comment]
Thanks for looking into this @tamayok . I'll forward the question to our Analytics team. I take it those two use different URLs to the configuration but we can only change one of them, right?

**Comment by langerhans** [comment]
I just got confirmed that we have Tag Management enabled and Tealium Collect disabled in our publish settings.

**Comment by tamayok** [comment]
@langerhans I've tested this, and it runs as expected. Are you setting the URL to the mobile.html prior to calling `Tealium.createInstance()`?

**Comment by langerhans** [comment]
Yes, I do. I'll try it again and debug it through Fiddler again. It seemed pretty obvious to me that the instance creation was successful, as I saw the environment change as expected to our dev, qa or prod environment respectively. Here's the code, without evaluation of the environment:

```
Tealium.Config tealiumConfig = Tealium.Config.create(application,
        TEALIUM_CONFIG.ACCOUNT,
        TEALIUM_CONFIG.PROFILE,
        tealiumEnv);
tealiumConfig.setOverrideTagManagementUrl(utagUrl);
tealiumConfig.getDispatchValidators().add(Tracking.createDispacthValidator());
Tealium instance = Tealium.createInstance(TEALIUM_CONFIG.INSTANCE, tealiumConfig);
```

**Comment by tamayok** [comment]
Aah, you'll need to enable the WebView and the cookie manager as well. You'll want to add the following listeners and methods prior to creating your instance:

`// (OPTIONAL) Enable all cookies (if desired)
        config.getEventListeners().add(createCookieEnablerListener());

  // (OPTIONAL) Get the WebView with UTag loaded
       config.getEventListeners().add(createWebViewLoadedListener());`

Take a look at TealiumHelper.java to add the `createCookieEnablerListener()` and `createWebViewLoadedListener()` here:  https://github.com/Tealium/tealium-android/blob/master/Samples/ExampleApp%2BTealium/app/src/main/java/com/tealium/example/helper/TealiumHelper.java 

Just a quick note: These two will be default enabled in our next release. You'll currently have to add the two lines above to continue. 

Please let me know if you need more help.

**Comment by langerhans** [comment]
Thank you for this hint. I can at least confirm that the SDK now tries to load the mobile.html from the specified location.

But... It only works for the `qa` and `dev` environments. As soon as I switch to `prod`, the WebView doesn't even get loaded. The respective logging listener never logs anything. Using the same URL and `qa` actually calls the URL, so its not an issue with the URL. 

Also, can you confirm, that the SDK will fall back to the Tealium backend if it receives a HTTP error (in my case 404) from the URL from the override? At least that's what I see in Fiddler.

**Comment by langerhans** [comment]
Okay, so I poked around a little deeper and it doesn't log anything with `prod` set as environment. Would be cool if the API consumer could decide about that ;)

Anyway, we have solved the issue server side, so I'm closing this myself.
