### ISSUE TITLE
Way to opt-out tracking by user

### ISSUE THREAD

**Issue by Thorsten1976** [Tealium/tealium-android#2]
Tealium 4.1.x had an enable/disable functionality.

How we can disable / enable tracking programmatically (e. g. an opt-out switch selectable by the user for legal reasons)? Per-user setting.

**Comment by jalakoo** [comment]
Hi Thorsten,

You can use the the DispatchValidator (http://tealium.github.io/tealium-android/) shouldDrop() function for this.  By having this function check your user setting or if the setting flips a flag checked by this function, you could suppress all calls by having it return 'true'.
