### ISSUE TITLE
Unable to import TealiumAdIdentifier

### ISSUE THREAD

**Issue by OmkarAmberkar** [Tealium/tealium-android#21]
I tried to import via [Maven](https://github.com/Tealium/tealium-android/tree/master/Support/AdIdentifier#option-2-maven-dependency) and was unable to import TealiumAdIdentifier.

**Comment by craigrouse** [comment]
@OmkarAmberkar did you get some kind of error when trying to import the module?

**Comment by OmkarAmberkar** [comment]
Nope, everything was fine. Should I download the .aar and include it in my dependencies until this is taken care of?

**Comment by OmkarAmberkar** [comment]
Even importing .aar did not work. Did you guys proguard your .aar? you might have to keep the class name in proguard.

**Comment by OmkarAmberkar** [comment]
Seems like the TealiumAdIdentifier.class has been renamed to AdIdentifier.class
You might want to update your README.md file

**Comment by craigrouse** [comment]
Thanks @OmkarAmberkar. We'll look into it. Not too sure what's happened, but we'll get it fixed. Thanks for the pointers.

**Comment by craigrouse** [comment]
@OmkarAmberkar we were never able to reproduce this issue locally. Please get in touch with our support team if the problem persists (support@tealium.com). Thanks.
