### ISSUE TITLE
How do I disable the logs?

### ISSUE THREAD

**Issue by OmkarAmberkar** [Tealium/tealium-android#22]
I am really frustrated with the amount of logs that tealium create and I cannot disable it. It makes stuff really difficult to debug. Is there a way to disable it?

**Comment by jalakoo** [comment]
Hi @OmkarAmberkar,
The logs can be disabled by either:
a) Changing the 'environment' variable in the config from 'dev' to 'prod'
b) In Tealium's TIQ dashboard: Publish Settings: Mobile Publish Settings:  Set Log override to 'Prod' or 'None'

**Comment by craigrouse** [comment]
@OmkarAmberkar we have now added the ability to override the log level at init time for the library. Please see here for details: https://community.tealiumiq.com/t5/Tealium-for-Android/Adding-Tealium-to-Your-Android-App/ta-p/16846

I'm closing this issue now, but please let me know if you have any further issues.
