### ISSUE TITLE
Tealium-5.3.0: Queued {} because the dispatcher is not ready

### ISSUE THREAD

**Issue by siripin701** [Tealium/tealium-android#27]
When I call for trackEvent() or trackView(), the log printed out that it's queued because the dispatcher is not ready. And, it has never been sent. Please advice.

To concise the log, I have removed the actual data that I sent and put <key>:<value> in the below log instead.

06-26 22:03:09.267 D/Tealium-5.3.0: Queued { key:value } because the dispatcher is not ready

06-26 22:03:09.282 V/Tealium-5.3.0: Fetching publish settings from https://tags.tiqcdn.com/utag/\<account\>/\<profile\>/dev/mobile.html?platform=android&device_os_version=7.0&library_version=5.3.0…

06-26 22:03:09.506 V/Tealium-5.3.0: No changes in Mobile Publish Settings detected

**Comment by craigrouse** [comment]
@siripin701 I just checked your profile, and I can see that the remote publish settings have not been activated for version 5+ of the SDK. Currently, only the publish settings for v4.1 are active. I would advise speaking to the person who administers your Tealium iQ account and asking them to activate these settings for you: https://community.tealiumiq.com/t5/Mobile-Libraries/Mobile-Publish-Settings/ta-p/13633

**Comment by siripin701** [comment]
I have contacted my Admin and he has activated this setting as you recommended. However, I still got the same response " the dispatcher is not ready" when I tested again. Please advise.

**Comment by craigrouse** [comment]
@siripin701 I just checked, and the settings have not yet been enabled in your profile. You need to make sure your admin presses the "+ Add Version" button in the UI, and select the v 5.0 settings as shown in the document I shared. The profile then needs to be published for the settings to be made active.

**Comment by siripin701** [comment]
Thank you. It seems to work now.

**Comment by craigrouse** [comment]
Thanks @siripin701. I'll close this issue, but let us know if you need anything else.
