### ISSUE TITLE
Validating the Android Installation

### ISSUE THREAD

**Issue by siripin701** [Tealium/tealium-android#28]
How to validate my android installation? 
I have followed this instruction https://community.tealiumiq.com/t5/Tealium-for-Android/Validating-Your-Android-Installation/ta-p/16852

1) As Non-AudienceStream Customers: I have added Tealium Collect tag and enable the Tealium Collect dispatch service. Where can I see this "Discover > Live Events" menu?

2) In the console log (logcat), I have added createDispatchValidator()  and seen the following. Does that mean everything works?

> Sending dispatch: { key:value }
> 06-28 21:34:21.053 V/Tealium-5.3.0: Sending data to https://collect.tealiumiq.com/vdata/i.gif?tealium_vid=1880b56cc982427491adda58101f6eab&tealium_account=schibsted&tealium_profile=main&device=Unknown+Android+SDK+built+for+x86&.......................&screen_title=Result_page
> 06-28 21:34:21.053 D/Tealium-5.3.0: Sent new dispatch {key:value,"page_name":"Result_page"}

3) I have also added createWebViewLoadedListener() and createLoggerRemoteCommand() but none of the log inside  these two methods got printed out. Any idea why?

`Tealium.Config config = Tealium.Config.create(application,
                ACCOUNT_NAME,
                PROFILE_NAME,
                ENVIRONMENT_NAME);`
`config.getEventListeners().add(createWebViewLoadedListener());`
`config.getDispatchValidators().add(createDispatchValidator());`
`final` Tealium instance = Tealium.createInstance(INSTANCE, config); `instance.addRemoteCommand(createLoggerRemoteCommand());`

And the actual code for those methods are exactly the same as what you provide in the sample code.

4) I got a tag vendor, called "AT Internet SmartTag"  (UID 49). After upgrade to this v5.3 version, I can't see any more tagging result in AT Internet. What did I miss?

**Comment by craigrouse** [comment]
@siripin701 since your question is related to your implementation, rather than the library itself, please contact our support team on support@tealium.com, and they will be able to help you validate your config. At first glance, it looks like everything is configured correctly to me. We prefer to keep account-specific information out of the public github repo where possible, so I will redact the identifying features of your comment, and close it off.
