### ISSUE TITLE
Library manifest should be as empty as possible

### ISSUE THREAD

**Issue by langerhans** [Tealium/tealium-android#3]
Hello,

the library's manifest seems to set `allowBackup="true"` which either

1) Lets the manifest merger fail if the app already set this attribute to false
2) Explicitly allows backups for the app (although that is default behavior, a library like this should not  touch such attributes)

```
Error:Execution failed for task ':dbtickets:processConsumerDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:46:9-36
  	is also present at [:tealium-5.0.3:] AndroidManifest.xml:14:18-44 value=(true).
  	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:44:5-495:19 to override.
```

Workaround is to ignore the attribute per suggestion

**Comment by tamayok** [comment]
In the latest release 5.0.4, we removed this allowBackup attribute in the manifest file.
