### ISSUE TITLE
StrictMode policy violation error triggered by database I/O done on UI thread

### ISSUE THREAD

**Issue by hanghildegard** [Tealium/tealium-android#40]
When using Tealium with StrictMode on, we get StrictMode policy violation error and according to our logs it is caused by Tealium performing database I/O on UI thread.

Here is an extract from logcat:

> StrictMode policy violation; ~duration=10 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=196671 violation=2
>                                                                              at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1440)
>                                                                              at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1042)
>                                                                              at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:843)
>                                                                              at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
>                                                                              at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
>                                                                              at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
>                                                                              at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
>                                                                              at com.tealium.internal.data.DispatchStore.dequeueDispatches(DispatchStore.java:100)
>                                                                              at com.tealium.library.c.g(DispatchRouter.java:342)
>                                                                              at com.tealium.library.c.onWebViewLoad(DispatchRouter.java:162)
>                                                                              at com.tealium.internal.b.r.a(WebViewLoadMessenger.java:20)
>                                                                              at com.tealium.internal.b.r.a(WebViewLoadMessenger.java:7)
>                                                                              at com.tealium.library.e$1.c(MessageRouterFactory.java:210)
>                                                                              at com.tealium.library.e$1.a(MessageRouterFactory.java:136)
>                                                                              at com.tealium.internal.dispatcher.WebViewDispatcher$5.onPageFinished(WebViewDispatcher.java:437)
>                                                                              at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:196)
>                                                                              at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:70)
>                                                                              at android.os.Handler.dispatchMessage(Handler.java:106)
>                                                                              at android.os.Looper.loop(Looper.java:164)
>                                                                              at android.app.ActivityThread.main(ActivityThread.java:6494)
>                                                                              at java.lang.reflect.Method.invoke(Native Method)
>                                                                              at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
>                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

It seems that the problem is here: 

> com.tealium.internal.data.DispatchStore.dequeueDispatches(DispatchStore.java:100)

Please fix this as soon as possible.

**Comment by tamayok** [comment]
@hanghildegard Thank you for reporting this. We'll look further into it.

**Comment by craigrouse** [comment]
@hanghildegard The updated SDK has now been released, including this fix (thanks to @tamayok for her hard work tracking down and fixing this). All database IO is now forced to run on a background thread.
