### ISSUE TITLE
Weak Cipher Suites

### ISSUE THREAD

**Issue by mikewmerritt** [Tealium/tealium-android#53]
I was directed here by the product support team.  Per a security scan by my company's information protection team, I've been made aware of several weak SSL cipher suites in the jar for the 5.5 version. The team is asking that the identified cipher suites be removed.

The suites identified: 

- TLS_EDCHE_ECDSA_WITH_AES_128_CBC_SHA
- TLS_EDCHE_ECDSA_WITH_AES_256_CBC_SHA
- TLS_EDCHE_RSA_WITH_AES_128_CBC_SHA
- TLS_EDCHE_RSA_WITH_AES_256_CBC_SHA
- TLS_RSA_WITH_AES_128_CBC_SHA
- TLS_RSA_WITH_AES_256_CBC_SHA

Please let me know if there are any questions.  This is not really my area of expertise so I'm happy to connect the jar developers with folks from my side if needed.

**Comment by tygavin** [comment]
These all appear to be enabled by default in Android API.  Do you have a reference that indicates these are considered "weak"?  Do you know of an outstanding update request for Android API to remove these from being default?

- https://developer.android.com/reference/javax/net/ssl/SSLEngine

I did a quick test using 'openssl' to our data collection endpoint.  This currently supports "ECDHE-RSA-AES128-GCM-SHA256" cipher so this will be the one used for data collection requests over SSL (as opposed to those in your list.)

`$ openssl s_client -connect collect.tealiumiq.com:443`

**Comment by mikewmerritt** [comment]
I'm pursuing some answers to your questions above, and the observation about TLS 1.3.

**Comment by tygavin** [comment]
Closing this issue.  The assumption is that any updates outside of Android default behavior would be done at the application level.
