### ISSUE TITLE
Crash on 5.6.1 -> Lcom/tealium/library/A

### ISSUE THREAD

**Issue by bbarrue** [Tealium/tealium-android#82]
Hey there I am updating our Tealium library from 5.4.2 to 5.6.1 however the library no longer initializes and crashes when trying to create our Configuration.

Getting the following error:
`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tealium/library/A;
        at com.tealium.library.Tealium$Config.create(Tealium.java:1)`

**Comment by jameskeith** [comment]
Hi @bbarrue 
I believe this was caused by a bug in the gradle plugin version that we had updated to for that release - please can you retry on v5.7.0 or above?
thanks

**Comment by bbarrue** [comment]
@jameskeith that one works! Thank you.

5.6.1 is currently listed in your documentation on site so might want to address that :)

**Comment by jameskeith** [comment]
glad to hear it's working
thanks for heads up, we'll get that updated asap.
